theme: jekyll-theme-minimal
title: Welcome to the BioData Society Website!
description: A Website for the BioData Society at Anglia Ruskin University

twitter_username: aru_biodata
github_username:  BioDataSoc
